name: Integration Tests & HACS Validation

on: [push, pull_request]

jobs:
  test_and_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          pip install -r requirements_test.txt
      - name: Run pytest Suite
        run: pytest tests/
      - name: HACS Validation
        uses: hacs/action@main
        with:
          category: integration
