name: Lint & Code Style

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install Linting Tools
        run: pip install ruff black
      - name: Run Ruff Linter
        run: ruff check custom_components/pec_smarthub
      - name: Run Black Formatter Check
        run: black --check custom_components/pec_smarthub
